source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!

install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCamera', :path => '../../node_modules/@capacitor/camera'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pushwoosh
  pod 'Pushwoosh', '~> 6.7.9'
end

# Elimina o comenta este bloque
# post_install do |installer|
#   assertDeploymentTarget(installer)
# end
